FROM alpine as builder

RUN apk add --no-cache --update nodejs npm \
  && node --version \
  && npm config set registry https://registry.npm.taobao.org

ENV NODE_ENV 16.18.0

WORKDIR /usr/app

COPY package.json .
RUN npm install
COPY . .

RUN npm run build
# /usr/app/build  <-- build files

# FROM nginx
# COPY --from=builder /usr/app/build /usr/share/nginx/html