name: docker-react
on:
  push:
    branches:
      - 'master'
jobs:
  # Build_Image_and_Test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     -
  #       name: Checkout
  #       uses: actions/checkout@v3

  #     -
  #       name: Setup Node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 16
  #         cache: 'npm'

  #     -
  #       name: Docker login
  #       uses: docker/login-action@v2
  #       with:
  #         username: wentaozhai
  #         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  #     - 
  #       name: Build Image
  #       run: |
  #         docker build -f Dockerfile.dev -t zhaiwentao/docker-react .

  #     -
  #       name: Test
  #       run: docker run -e CI=true zhaiwentao/docker-react npm run test

  Build_Static_File_and_Deploy:
    runs-on: ubuntu-latest
    # if: ${{ always() }} # 总是执行 工作流环境需关闭
    # needs: Build_Image_and_Test # 执行顺序
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      -
        name: Docker login
        uses: docker/login-action@v2
        with:
          username: wentaozhai
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      -
        name: Build Static file
        run: docker build -f Dockerfile.prod -t zhaiwentao/docker-react-build .
      
      -
        name: CP Static File to Local System
        run: docker cp $(docker run -d -e CI=true zhaiwentao/docker-react-build):/usr/app/build ./build

      -
        name: GitHub Pages Deploy action
        uses: peaceiris/actions-gh-pages@v3
        with: 
          github_token: ${{ DOCKER_REACT_GITHUB_TOKEN }}
          publish_dir: ./build