name: docker-react
on:
  push:
    branches:
      - 'master'
  jobs:
    buildANDtest:
      runs-on: ubuntu-latest
      steps:

        -
          name: Checkout
          uses: actions/checkout@v3

        -
          name: test
          run: docker run -e CI=true npm run test

        -
          name: build
          run: docker run -e CI=true npm run build
        
        - name: check
          run: ls
