name: docker-react
on:
  push:
    branches:
      - 'master'
jobs:
  Build_Image_and_Test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      -
        name: Docker login
        uses: docker/login-action@v2
        with:
          username: wentaozhai
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - 
        name: Build Image
        run: |
          docker build -f Dockerfile.dev -t zhaiwentao/docker-react .

      -
        name: Test
        run: docker run -e CI=true zhaiwentao/docker-react npm run test

  Build_Static_File_and_Deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      -
        name: Docker login
        uses: docker/login-action@v2
        with:
          username: wentaozhai
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      -
        name: Build Static file
        run: docker build -f Dockerfile.prod -t zhaiwentao/docker-react-build .
      
      -
        name: check file
        run: docker run -it zhaiwentao/docker-react-build ls